Improve documentation of Gtk.TreeStore()
sebp/PyGObject-Tutorial pull request #187
Opened 2020-12-22 19:45 UTC by cjmayo

- Add a snippet with text for Gtk.TreeStore.append()
- Use Gtk.TreeModel.foreach() instead of custom Python code

---

Use keyword arguments with Gtk.Treeview() constructor

Positional arguments are deprecated and be consistent.

2020-12-28 19:29 UTC, cjmayo commented
Add a mention of Gtk.TreeModelFilter.set_visible_column().

2021-01-04 17:07 UTC, sebp requested changes
Thanks for your help to improve the tutorial. Would be great if you could apply the two changes I highlighted.

2021-01-04 17:07 UTC, sebp commented on source/treeview.txt
> +For a tree store you must specify an existing row to append the new row to,
Replace `tree store` with
```
:class:`Gtk.TreeStore`
```

2021-01-04 17:07 UTC, sebp commented on source/treeview.txt
> +For a list store:
Replace `list store` with:
```
:class:`Gtk.ListStore`
```

2021-01-05 19:31 UTC, cjmayo commented on source/treeview.txt
> +For a tree store you must specify an existing row to append the new row to,
> Thanks for your help to improve the tutorial. Would be great if you could apply the two changes I highlighted.

No problem. Both done.

2021-01-05 19:31 UTC, cjmayo commented on source/treeview.txt
> +For a list store:
Done.

2021-01-05 19:43 UTC, merged